[versions]
processor = "2025.1-SNAPSHOT"

kotlin = "2.2.21"
target-jdk = "11"
build-jdk = "17"
build-plugins = "2025.12"

api = "2024.2"
parser = "2026.1-SNAPSHOT"

jacoco = "0.8.7"

[libraries]
openapi-processor-api = { module = "io.openapiprocessor:openapi-processor-api", version.ref = "api" }
openapi-parser-bom = { module = "io.openapiprocessor:openapi-parser-bom", version.ref = "parser" }
openapi-parser-parser = { module = "io.openapiprocessor:openapi-parser" }
io-jackson = { module = "io.openapiprocessor:io-jackson" }
diff = { module = "io.github.java-diff-utils:java-diff-utils", version = "4.16" }

logback = "ch.qos.logback:logback-classic:1.5.22"

kotest-bom = "io.kotest:kotest-bom:6.0.7"
kotest-runner = { module = "io.kotest:kotest-runner-junit5" }
kotest-table = { module = "io.kotest:kotest-assertions-table" }
mockk = "io.mockk:mockk:1.14.7"

groovy-bom = "org.apache.groovy:groovy-bom:5.0.3"
spock = "org.spockframework:spock-core:2.4-groovy-5.0"

# for buildSrc convention plugins
plugin-build = { module = "io.openapiprocessor:build-plugins", version.ref = "build-plugins" }
plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

[plugins]
updates = { id = "com.github.ben-manes.versions", version = "0.53.0" }
